eureka:
  instance:
    hostname: localhost
  client:    fetch-registry: false
    register-with-eureka: false
    service-url:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka

  
     

server:  port: 8761
  
---
spring:  profiles: eureka-1  application:    name: eureka-1server:  port: 8761eureka:  instance:    hostname: eureka1.localhostother:  eureka:    host: localhost    port: 8762---spring:  profiles: eureka-2  application:    name: eureka-2server:  port: 8762eureka:  instance:    hostname: eureka1.localhostother:  eureka:    host: localhost    port: 8762