spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nicholas-Barbosa/tacocloud-config
          default-label: main
  application:    name: config-app     

server:  port: 8888